# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:23
from __future__ import unicode_literals

import acads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Topic')),
                ('files', models.FileField(upload_to=acads.models.get_file_path)),
                ('verified', models.BooleanField(default=False)),
                ('uploader_roll_no', models.CharField(max_length=100)),
                ('uploader_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=2)),
                ('subject_code', models.CharField(max_length=7)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acads.Subject'),
        ),
    ]
